---
output:
  html_document:
    toc: true
version: 0.1.1
author: Tamas Ryszard Sztanka-Toth, Nikolaos Karaiskos
email: tamasryszard.sztanka-toth@mdc-berlin.de, nikolaos.karaiskos@mdc.berlin.de
license: GPL
---

```{r knitr_options, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(
  autodep = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = NA
)
```

```{r libraries, include = F, cache=F}
library(tidyverse)
library(yaml)
library(knitr)
library(magrittr)
library(kableExtra)
library(cowplot)

theme_set(theme_cowplot(12))

cpalette <- list('orange' = '#D55E00', 'blue' = '#0072B2', 'green' = '#009E73', 'black' = '#000000', 'yellow' = '#F0E442', 
				 'grey' = '#999999', 'light_orange' = "#E69F00", 'light_blue' = "#56B4E9")

clrs = c('umis'=cpalette$light_orange, 'genes' = cpalette$light_blue,
         'reads'=cpalette$green, 'pcr'=cpalette$pink, 'pct_counts_mt'= 'black')

source(snakemake@params$r_shared_scripts)
```

```{r save_snakemake_object, echo = F}
#write_rds(snakemake, '/scratch/home/tsztank/snakemake.rds')
#snakemake <- read_rds('/scratch/home/tsztank/snakemake.rds')
```

```{r read_data, echo = F}
parameters <- read_yaml(snakemake@input$parameters_file)

parameter_stats <- parameters %>%
    as_tibble() %>%
    gather('metric', 'value')

obs_df <- read_table2(snakemake@input$obs_df) %>%
    mutate(pct_counts_mt = as.double(pct_counts_mt))
var_df <- read_table2(snakemake@input$var_df)

data_empty <- nrow(obs_df) == 0
```

### Overview

```{r create_overview_table, echo = F}
parameter_stats <- parameter_stats %>%
    rbind(c('UMI filter', snakemake@wildcards$umi_cutoff),
          c('# genes in data', nrow(var_df)),
          c('# of beads in data', nrow(obs_df)),
          c('median UMI', median(obs_df$n_counts)),
          c('median genes', median(obs_df$n_genes)))

parameter_stats %>%
    kbl(col.names=NULL) %>%
    kable_classic_2(full_width=F) %>%
    pack_rows('Sample info', 1, 7) %>%
    pack_rows('Data info', 8, 12)
```

### Histogram of metrics over beads

```{r data_empty, echo = F, eval = data_empty, results='asis'}
cat('This dataset has 0 beads passing the filters')
```

```{r plot_histogram_of_metrics, echo = F, fig.width=10, eval=!data_empty}
pl1 <- obs_df %>%
    select(cell_bc, n_counts, n_genes) %>%
    dplyr::rename(umis=n_counts,
                  genes=n_genes) %>%
    gather('obs', 'value', -cell_bc) %>%
    ggplot(aes(value, fill=obs)) +
        geom_histogram(bins=100) +
        scale_fill_manual(values=clrs) +
        facet_wrap(~obs, ncol=2, scales='free')

if (nrow(obs_df) > 50){
    pl1 <- pl1 +
        scale_x_log10() +
        annotation_logticks(sides='b') +
        labs(x='log(value)', y='count')
} else {
    pl1 <- pl1 +
        labs(x ='value', y='count')
}

pl2 <- obs_df %>%
    select(cell_bc, pct_counts_mt) %>%
    gather('obs', 'value', -cell_bc) %>%
    ggplot(aes(value, fill=obs)) +
        geom_histogram(bins=100) +
        scale_fill_manual(values=clrs) +
        facet_wrap(~obs, ncol=2, scales='free')+
        labs(x='value', y='count')

plot_grid(pl1,
          plot_grid(pl2, NULL, ncol=2, rel_widths=c(1.5,1), labels=""),
          ncol=1, rel_heights=c(1,1), labels="")
```


```{r check_completeness, echo = F, fig.size=10, fig.width=10}
obs_df <- obs_df %>%
    gather('res', 'cluster', starts_with('leiden'))

data_complete = F

if ('cluster' %in% obs_df){
    data_complete = T
}

fig_height=7
fig_width=7
```

```{r incompleteness_warning, eval=!data_complete, echo=F, results='asis'}
cat('### WARNING: data incomplete\n\n')
cat(paste0('This dataset has ', nrow(obs_df), ' cells passing the filter of ', snakemake@wildcards$umi_cutoff, ' and ', nrow(var_df), ' genes.\n\n'))
cat(paste0('This dataset is too small, so it couldn\'t be properly clustered and analysed automatically'))
```


```{r umap_text, eval=data_complete, echo =F, results='asis'}
cat('### UMAP plots using different resolutions\n\n')
```


```{r plot_umi_umap, eval=data_complete, echo=F}
obs_df <- obs_df %>%
    mutate(cluster = factor(cluster)) %>%
    mutate(log1p_total_counts = log2(1+total_counts))

barcode_file <- snakemake@input$barcode_file

get_column_name <- function(dat, possibilities){
    # parse column names
    cols <- dat %>% colnames

    for(pos in possibilities){
        if (pos %in% cols){
            return(pos)
        }
    }
}

if (!is.null(barcode_file)){
    fig_width=14

    # try reading as tabular
    coordinates <- read_csv(barcode_file)

    if(ncol(coordinates) < 2){
        coordinates <- read_tsv(barcode_file)}

    # find the names of the columns
    cell_bc_col <- get_column_name(coordinates, c('barcodes', 'barcode', 'cell_bc')) 
    x_pos_col <- get_column_name(coordinates, c('xcoord', 'x_pos')) 
    y_pos_col <- get_column_name(coordinates, c('ycoord', 'y_pos')) 

    coordinates <- coordinates %>%
        dplyr::rename(cell_bc = cell_bc_col,
                      x_pos = x_pos_col,
                      y_pos = y_pos_col) %>%
        select(cell_bc, x_pos, y_pos) 

    obs_df <- obs_df %>%
        left_join(coordinates, by='cell_bc')

    obs_df %>%
        filter(res == 'leiden_0.2') %>%
        mutate(log1p_total_counts = log2(1+total_counts)) %>%
        arrange(log1p_total_counts) %>%
        ggplot(aes(x_pos, y_pos, color = log1p_total_counts)) +
            geom_point(size = 0.1)+
            coord_fixed()+
            scale_color_viridis_c(option = "magma") +
            ggtitle('UMI distribution in 2D')

}
```

```{r plot_clusters_umap_puck, echo =F, fig.height=fig_height, fig.width=fig_width, eval=data_complete}
plots <- list()

for (i in obs_df %$% res %>% unique){
    pl1 <- obs_df %>%
        filter(res == i) %>%
        ggplot(aes(umap_0, umap_1, color = cluster)) +
            geom_point(size=0.2, alpha=0.8) +
            coord_fixed() +
            facet_wrap(~res, ncol = 1) +
            guides(colour = guide_legend(override.aes = list(size=3)))

    if (!is.null(barcode_file)) {
        pl2 <- obs_df %>%
            filter(res == i) %>%
            ggplot(aes(x_pos, y_pos, color = cluster)) +
                geom_point(size=0.1, alpha=0.8) +
                coord_fixed() +
                facet_wrap(~res, ncol = 1) +
                guides(colour = guide_legend(override.aes = list(size=3)))

        print(plot_grid(pl1, pl2))
    } else {
        print(pl1)
    }
}
```

### Marker tables

under development...

```{r load_top_cluster_markers, echo = F, eval=F}
top10_marker_table <- read_table2(snakemake@input$cluster_markers)

top10_marker_table %>%
    filter(pvals_adj <0.5, pts > 0.01) %>%
    filter(resolution == 0.2) %>%
    kbl() %>%
    kable_classic_2(full_width = F)
```

```{r read_expr_df, echo = F}
expr_df <- read_table2(snakemake@input$long_expr_df)
```

```{r plot_selected_genes, echo = F, fig.height=fig_height, fig.width=fig_width, eval=data_complete}
plot_gene <- function(gene_smbl){
    gene_expr <- expr_df %>%
        filter(gene == gene_smbl)

    gene_expr <- obs_df %>%
        filter(res == 'leiden_0.2') %>%
        left_join(gene_expr, by = 'cell_bc') %>%
        replace_na(list(expr = 0, gene=gene_smbl)) %>%
        arrange(expr)

    pl1 <- gene_expr %>%
        ggplot(aes(umap_0, umap_1, color = expr)) +
            geom_point(size=0.1) +
            coord_fixed() +
            facet_wrap(~gene) +
            scale_color_viridis_c(option = "inferno", direction=-1) +
            labs(color='UMI')

    if(!is.null(barcode_file)){
        pl2 <- gene_expr %>%
            ggplot(aes(x_pos, y_pos, color = expr)) +
                geom_point(size=0.1) +
                coord_fixed() +
                facet_wrap(~gene) +
                scale_color_viridis_c(option = "inferno", direction=-1) +
                labs(color='UMI count')
        print(plot_grid(pl1, pl2))
    } else {
        print(pl1)
    }
}

plot_gene('Slc17a7')

plot_gene('Map2')

plot_gene('Olig1')
```
